version: "3.8"

services:
  minecraft:
    build: .
    container_name: minecraft-server
    ports:
      - "${PORT:-25565}:25565"
    volumes:
      - ./data:/minecraft/data
    environment:
      RAM: "2G"
      PORT: "25565"
    restart: unless-stopped
